spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
  kafka:
    bootstrap-servers: 127.0.0.1:9092

kakava-client:
  client-id: temp
  grant-type: password
  username: temp
  password: temp
  base-url: https://app-kkv-be-test.azurewebsites.net
  auth-path: /Token
  shows-path: /event/show
  tickets-path: /order
  using-ticket-path: /arena/admission